version: '3'

services:

    db:
        image: mysql
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 33060:3306
        environment:
            MYSQL_DATABASE: php72
            MYSQL_ROOT_PASSWORD: password

    php:
        build: ./php-fpm
        volumes:
            - ./www:/var/www:cached
        ports:
            - 9000:9000
        links:
            - db

    nginx:
        build: ./nginx
        restart: always
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx/:/var/log/nginx:cached
        ports:
            - 8080:80
        links:
            - php